### ISSUE TITLE
Question about incomplete data

### ISSUE THREAD

**Issue by emm1R** [sidhomj/DeepTCR#35]
Hi again,
How does DeepTCR deal with columns that have some missing values? For example, if there are some TCRBs that are missing the D gene.

**Comment by sidhomj** [comment]
it represents missing information as that precisely. "unknown" is provided as the input into the model.

**Comment by emm1R** [comment]
I noticed that when aggregate_by_aa is True the code has `agg_dict[col] = 'first'`. Should the first TCR have missing values, wouldn't it be better to try and check if there is a TCR with values in all columns?

**Comment by emm1R** [comment]
Also, is it normal for two TCRBs to be assigned to two different clusters even though the only difference between them is that the other one is missing the D gene information?

**Comment by sidhomj** [comment]
Thank you for the suggestion! Will definitely consider how to implement this in future versions. However, at this time, since different sequencing platforms denote "unknown," we need to consider how to account for this. That being said, we do not expect a major difference in the results or two TCR's with identical sequences to fall very far in sequence space due to a different d-segment. If you think your data set really requires this to be correct, you can always parse the datas you like, and pass it to DeepTCR through the Load_Data method rather than the Get_Data method.
